apiVersion: v1
kind: Pod
metadata:
  name: bastion-test
spec:
  containers:
    - name: test-container
      image: claudious96/ssh-bastion:latest
      imagePullPolicy: Always
      volumeMounts:
        - name: config-volume
          mountPath: /home/bastion/.ssh
  volumes:
    - name: config-volume
      configMap:
        name: auth-keys-bastion
        defaultMode: 0444
  restartPolicy: Never
