apiVersion: apps/v1
kind: Deployment
metadata:
  name: ssh-bastion
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: ssh-bastion
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2020-09-12T12:59:32Z"
      creationTimestamp: null
      labels:
        app: ssh-bastion
    spec:
      containers:
      - args:
        - -D
        - -e
        - -f
        - /etc/ssh/sshd_config_custom
        command:
        - /usr/sbin/sshd
        image: claudious96/ssh-bastion:latest
        imagePullPolicy: Always
        name: bastion
        ports:
        - containerPort: 2222
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /home/bastion/.ssh
          name: config-volume
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: config-volume
          configMap:
            name: auth-keys-bastion
            defaultMode: 0444
---
apiVersion: v1
data:
  authorized_keys: |
    # Just a comment to fill in the configmap and start the pod
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: auth-keys-bastion

