# permissions for end users to edit bastions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: bastion-editor-role
rules:
- apiGroups:
  - tenant.crownlabs.polito.it
  resources:
  - bastions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tenant.crownlabs.polito.it
  resources:
  - bastions/status
  verbs:
  - get
