# permissions for end users to view bastions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: bastion-viewer-role
rules:
- apiGroups:
  - tenant.crownlabs.polito.it
  resources:
  - bastions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - tenant.crownlabs.polito.it
  resources:
  - bastions/status
  verbs:
  - get
