
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - tenant.crownlabs.polito.it
  resources:
  - bastions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tenant.crownlabs.polito.it
  resources:
  - bastions/status
  verbs:
  - get
  - patch
  - update
